spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: svn12
  jpa:
    hibernate:
      ddl-auto: create-drop
hibernate:
  properties:
    hibernate.show_sql: true
server:
  port: 8081
